name: Frontend CI Workflow

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  push:
    branches:
        - main

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

# Jobs defined in the workflow
jobs:
  build-and-test-eslint:
    runs-on: ubuntu-latest

    # Only when code in the frontend application changes
    defaults:
      run:
        working-directory: starter/frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: install dependency
        run: npm i
      
      - name: Run test eslint
        run: npm run lint -- --fix

  build-and-test-react-script:
    runs-on: ubuntu-latest

    # Only when code in the frontend application changes
    defaults:
      run:
        working-directory: starter/frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: install dependency
        run: npm i
      
      - name: Run test
        run: npm test --passWithNoTests

  build-docker-file-for-fe:
    needs: [build-and-test-eslint, build-and-test-react-script]
    runs-on: ubuntu-latest
    steps:
      - name: build docker file
        run: docker build -t movies-cicd-image ../starter/frontend
    